paths:
  /api/products:
    get:
      summary: Obtiene todos los productos
      tags:
        - Productos
      responses:
        "200":
          description: Los productos fueron devueltos satisfactoriamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/product"
        "500":
          description: Error del servidor. Usualmente generando la query o falla la conexion a la DB
  /api/products/{pid}:
    get:
      summary: Obtiene un producto
      tags:
        - Productos
      parameters:
        - name: uid
          in: path
          required: true
          description: ID del producto que se busca
          schema:
            $type: String
      responses:
        "200":
          description: Producto encontrado
          content:
            application/json:
              schema:
                $ref: "#components/schemas/product"
components:
  schemas:
    Success:
      type: object
      properties:
        status:
          type: String
          description: success or error
        message:
          type: String
          description: aclarando que ocurrio
      example:
        status: success
        message: Product updated
    product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: ID auto generado by mongo
        title:
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Descripcion del producto
        code:
          type: String
          description: Codigo del producto
        price:
          type: Number
          description: Precio del producto
        status:
          type: String
          description: Estado del producto
        stock: 
          type: Number
          description: Cantidad existente del producto
        thumbnails: 
          type: String
          description: URL del producto
        onwer: 
          type: String
          description: creador del producto
          
      example:
        _id: ObjectId("64dfdf7cdd397dac259103c1"),
        title: Pizza Margarita,
        description: Clásica pizza italiana con tomate, mozzarella y albahaca.,
        code: MARG01,
        price: 9.99,
        status: true,
        stock: 25,
        thumbnails: http://localhost:8080/images/margeritapizza.jpg,
        owner: "admin"
  